name: Terraform Deploy

on:
  push:
    branches:
      - main
      - development
    paths:
      - 'tf-code/**'
  pull_request:
    branches:
      - main
    paths:
      - 'tf-code/**'

env:
  TF_VERSION: 1.6.0

jobs:
  terraform:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tf_working_dir:
          - ./tf-code/workspace-a
          - ./tf-code/workspace-b
          - ./tf-code/workspace-c
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Format Check
        working-directory: ${{ matrix.tf_working_dir }}
        run: terraform fmt -check -recursive

      - name: Terraform Init
        working-directory: ${{ matrix.tf_working_dir }}
        run: terraform init

      - name: Terraform Validate
        working-directory: ${{ matrix.tf_working_dir }}
        run: terraform validate

      - name: Terraform Plan
        working-directory: ${{ matrix.tf_working_dir }}
        run: terraform plan -out=tfplan
        env:
          TF_VAR_github_token: ${{ secrets.TF_GITHUB_TOKEN }}
